### ISSUE TITLE
TODO list of enhancements

### ISSUE THREAD

**Issue by Ferdzz** [Ferdzz/PlaceableItems#72]
### This issue is a bucket of all the TODOs

Any of these can be picked up by anyone. Feel free to open forks and contribute. If you need help setting up or hints as to how to implement these features, feel free to contact me through the Discord or comment on this issue.

Gameplay enhancements:
- [ ] Add animated particles to blaze powder
- [ ] Allow the player to right click the egg when placed, with a chance to spawn a chicken
- [ ] Implement `FluidHolder` in the buckets to allow them to be filled / unfilled
- [ ] Make the placed slimeball bouncy
- [ ] Allow for writing in the writable book when placed
- [ ] Make some sort of progress when eating, not instantly on right click

Technical enhancements:
- [ ] Unit testing
- [ ] Move the `TileEntity` registration to a dedicated class
- [ ] Cache `BlockItem`s when placing
- [ ] Generalize `BoneBlockComponent` to allow for dropping any `ItemStack`
